name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: "Create env file"
        run: echo "${{ secrets.ENV }}" > .env.production
      - name: Build Docker Image tu Dockerfile
        run: docker build --progress=plain -t quan/my-app:v0
      - name: Login Docker Hub
        run: docker login -u ${{ secrects.DOCKERHUB_USERNAME }} -p ${{ secrects.DOCKERHUB_PASSWORD }}
      - name: Push Docker image to Docker Hub
        run: docker push quan/my-app:v0

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "Executing remote ssh commands using password"
        uses: appleboy/ssh-action@v1.0.0
        # Tham số VPS (Truy cập vào VPS và pull Image từ Docker Hub về chạy Contianer)
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.HOST_USERNAME}}
          password: ${{ secrets.HOST_PASSWORD}}
          post: ${{ secrets.POST}}
          # Các câu lệnh thực thi trên VPS
          script: |
            docker login -u ${{ secrects.DOCKERHUB_USERNAME }} -p ${{ secrects.DOCKERHUB_PASSWORD }}
            docker pull quan/my-app:v0
            docker stop my-container
            docker rm my-container
            docker run -dp 3000:3000 my-container